export FM_HOME="$PWD/.test-live/home"
export FM_PROCEVENT_CLAIM_ROOT="$PWD/.test-live/claims"
export LAVISH_AXI_STATE_DIR="$PWD/.test-live/lavish-state"
export LAVISH_AXI_HOST=127.0.0.1
export LAVISH_AXI_PORT=18487
export LAVISH_AXI_TELEMETRY=off
export CHROME_DEVTOOLS_AXI_SESSION=fm-lab-owner-reply
export CHROME_DEVTOOLS_AXI_PORT=18488
export CHROME_DEVTOOLS_AXI_USER_DATA_DIR="$PWD/.test-live/chrome-profile"
unset FM_ROOT_OVERRIDE FM_STATE_OVERRIDE FM_DATA_OVERRIDE FM_CONFIG_OVERRIDE FM_PROJECTS_OVERRIDE FM_GATE_REFUSE_BYPASS
